CREATE TABLE cards (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       card_number VARCHAR(255) NOT NULL,
                       expiration_date DATE NOT NULL,
                       card_type SMALLINT NOT NULL,  -- Assuming the CardType enum will be stored as a string
                       balance DOUBLE PRECISION NOT NULL,
                       created_at DATE NOT NULL,
                       user_id BIGINT,
                       FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);