CREATE TABLE users (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(255) NOT NULL,
                       surname VARCHAR(255) NOT NULL,
                       birthdate DATE NOT NULL,
                       gender SMALLINT NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL
);